# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build reorg-notifier`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t reorg-notifier`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system reorg-notifier && \
          adduser --system -G reorg-notifier reorg-notifier

COPY dist/reorg-notifier reorg-notifier
RUN chown -R reorg-notifier:reorg-notifier .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix reorg-notifier --omit=dev -f install

CMD [ "node", "reorg-notifier" ]
